-- Fix: "duplicate key value violates unique constraint invoices_business_id_invoice_number_key"
--
-- Root cause: invoice numbers were generated by counting existing rows
-- (SELECT count(*) FROM invoices WHERE business_id = ...) and doing count+1.
-- This collides whenever:
--   1. Two invoices are created concurrently (both read the same count), or
--   2. An invoice was ever deleted (count drops below the highest number used).
--
-- Fix: track a durable, atomically-incrementing counter per business and
-- hand out numbers via a single UPDATE ... RETURNING statement, which
-- Postgres serializes per-row — no two callers can ever get the same number.

ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS next_invoice_number integer NOT NULL DEFAULT 1;

-- Backfill: seed each business's counter to (highest existing invoice number + 1)
-- so numbering continues seamlessly instead of restarting at 1.
DO $$
DECLARE
  biz RECORD;
  max_num integer;
BEGIN
  FOR biz IN SELECT id FROM businesses LOOP
    SELECT COALESCE(MAX((regexp_match(invoice_number, '(\d+)$'))[1]::integer), 0)
      INTO max_num
      FROM invoices
      WHERE business_id = biz.id;

    UPDATE businesses
      SET next_invoice_number = max_num + 1
      WHERE id = biz.id AND next_invoice_number <= max_num;
  END LOOP;
END $$;

-- Atomically claim the next invoice number for a business.
-- Returns the sequence number (caller formats it with prefix/year/padding).
CREATE OR REPLACE FUNCTION get_next_invoice_number(p_business_id uuid)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_num integer;
BEGIN
  UPDATE businesses
    SET next_invoice_number = next_invoice_number + 1
    WHERE id = p_business_id
    RETURNING next_invoice_number - 1 INTO v_num;

  IF v_num IS NULL THEN
    RAISE EXCEPTION 'Business % not found', p_business_id;
  END IF;

  RETURN v_num;
END;
$$;

GRANT EXECUTE ON FUNCTION get_next_invoice_number TO authenticated, anon, service_role;
